### ISSUE TITLE
Add support for EBS as project source

### ISSUE THREAD

**Issue by njeirath** [njeirath/brenda-web#52]
Brenda supports URLs of the form ebs://snap-xxxxx, add support for this here as well.

**Comment by njeirath** [comment]
Suspect that the snapshot needs to be attached to the instance when it's created, need to figure out correct configuration to support that.

**Comment by njeirath** [comment]
Logs from attempted run:

```
ubuntu@ip-10-154-17-27:/mnt/brenda$ cat log 
RM task_count
RM task_last
MKDIR /mnt/brenda/tmp
Spot request ID: sir-029fr6cf
MKDIR /mnt/brenda/brenda-project.mount
*** ['/bin/mount', '/dev/xvdf1', '/mnt/brenda/brenda-project.mount']
mount: special device /dev/xvdf1 does not exist
Traceback (most recent call last):
  File "/usr/local/bin/brenda-node", line 112, in <module>
    main()
  File "/usr/local/bin/brenda-node", line 108, in main
    i.start()
  File "/usr/local/lib/python2.7/dist-packages/brenda/daemon.py", line 90, in start
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/brenda/daemon.py", line 143, in run
    self.func()
  File "/usr/local/bin/brenda-node", line 105, in <lambda>
    func = lambda : node.run_tasks(opts, args, conf)
  File "/usr/local/lib/python2.7/dist-packages/brenda/node.py", line 333, in run_tasks
    proj_dir = get_project(conf, blender_project)
  File "/usr/local/lib/python2.7/dist-packages/brenda/node.py", line 421, in get_project
    utils.mount(dev, proj_dir)
  File "/usr/local/lib/python2.7/dist-packages/brenda/utils.py", line 88, in mount
    system(["/bin/mount", dev, dir])
  File "/usr/local/lib/python2.7/dist-packages/brenda/utils.py", line 24, in system
    raise ValueError("command failed with status %r (expected %r)" % (ret, succeed))
ValueError: command failed with status 32 (expected 0)
```

**Comment by njeirath** [comment]
Added support for mounting a single EBS snapshot for now in #56 .

Can revisit to add support for multiple EBS snapshots at a later time.

**Comment by jldonovan3** [comment]
I came across this while looking for a solution for a problem I'm currently having with vanilla brenda ([see issue here](https://github.com/jamesyonan/brenda/issues/37)). You say here there's a difference between how device mapping works now as opposed to how brenda treated creating EBS volumes... I'm trying to connect an EBS volume with brenda-created instances, and I'm getting `bad-parameter` failures. The state says `Invalid device name /dev/sdf1` I can't even create an EBS volume with the `brenda-ebs` tool because I get the same "invalid device name" failure because the device name is `/dev/sdf1`.

I tried using the snapshot in brenda-web, and it looks like the worker again failed to launch. Do you have any idea for a solution to this in vanilla brenda?

**Comment by njeirath** [comment]
@jldonovan3 I put this together quite a while ago and haven't actually tried using an EBS volume in some time now so not positive if it all still works the same way here.  In any case, from what I recall there were 2 main changes that I had noticed. 

First, the EBS volumes are mounted to a different device than they used to be, mainly I believe (from your error message) the old way was to mount EBS volumes to `/dev/sdf1` whereas I believe block devices now get mounted to `/dev/sdf`.  This change goes into the payload used to actually create the EC2 instances (some details can be found [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html) )

The second change was that the brenda software that runs on the worker nodes expects the device to be mounted on `/dev/xvdf1` but in reality the device was getting mounted to `/dev/xvdf` so the solution there was to add the line `sudo ln /dev/xvdf /dev/xvdf1` to the startup script that also gets passed along to the EC2 instance during creation and is run when the instance starts up.

I believe those were the two primary changes although again it has been a while.  As long as things haven't changed again you should be able to use this tool to spin up EC2 workers for Brenda and have it successfully mount the EBS volumes and let brenda do it's thing.  Hope this helps and I'll look forward to hearing how it goes for you.

**Comment by jldonovan3** [comment]
@njeirath thanks for the reply! Appreciate it! 

It does seem like the "1" added to "sdf" is what might be confusing the spot request, since it looks like HVM instances don't accept EBS volumes mounted with the "1" at the end of the device name. Right now, the issue for me is somehow finding why or how brenda is designating the device name for my EBS snapshot on the instance as "/dev/sdf1". I'm not sure where it's getting that device name... whether it's in brenda or in boto. It looks like you were able to alter the .js script that runs brenda-web's service, but I'm not sure where vanilla brenda could be modified to assign device names to the device mapping. I'm more of a vfx guy than a python/AWS guy, so my ability to know my way around a tool like brenda is somewhat limited. 

And I did try it with brenda-web, and while it did launch the instance and the spot request seemed to work, the instance sat for a good hour without showing any activity. Is there a way within brenda-web to see the output one would get with `brenda-tool ssh tail log` to see what might be going on in the instance while the tasks are supposed to be running? I tried running `brenda-tool ssh tail log` while the instance launched with brenda-web was running, and there was no output.

Again, thanks for the help with this. It's been tough for me finding support for these tools, since they are pretty old by now.

**Comment by jldonovan3** [comment]
Update: So I found kinda a stupid-simple solution by modifying the `devs` sequence in the utils.py :

```
def blkdev(index, istore=False, mount_form=False):
    if istore:
        # instance store
        devs = ('b', 'c', 'd', 'e')
    else:
        # EBS
        devs = (
            'f', 'g1', 'h1', 'i1', 'j1', 'k1', 'l1', 'm1', 'n1', 'o1', 'p1',
            'f2', 'g2', 'h2', 'i2', 'j2', 'k2', 'l2', 'm2', 'n2', 'o2', 'p2',
            'f3', 'g3', 'h3', 'i3', 'j3', 'k3', 'l3', 'm3', 'n3', 'o3', 'p3',
            'f4', 'g4', 'h4', 'i4', 'j4', 'k4', 'l4', 'm4', 'n4', 'o4', 'p4',
            'f5', 'g5', 'h5', 'i5', 'j5', 'k5', 'l5', 'm5', 'n5', 'o5', 'p5',
            'f6', 'g6', 'h6', 'i6', 'j6', 'k6', 'l6', 'm6', 'n6', 'o6', 'p6',
            )
    if mount_form:
        return '/dev/xvd' + devs[index]
    else:
        return '/dev/sd' + devs[index]
```

Instead of 'f1', I changed it to 'f', and I only had to change the first one because I'm only attaching one EBS volume. So now when I try to mount the EBS volume, it mounts to `/dev/sdf`, which the HVM virtualization seems to like now. I had to run `brenda/setup.py` again after I made the change, and then it worked.

However, it didn't run the render process, I think because of the issue you pointed out... all my scene and project files were getting mounted to /dev/xvdf, and brenda wasn't starting up on the instance. I saw you plugged in the `sudo ln /dev/xvdf /dev/xvdf1` in your .js setup file.... do you think it would work if I plugged it in here in `brenda/run.py` ?

```
 if use_istore:
        # script to start brenda-node running
        # on the EC2 instance store
        iswd = conf.get('WORK_DIR', '/mnt/brenda')
        if iswd != login_dir:
            head += """\
# run Brenda on the EC2 instance store volume
B="%s"
sudo ln /dev/xvdf /dev/xvdf1
if ! [ -d "$B" ]; then
  for f in brenda.pid log task_count task_last DONE ; do
    ln -s "$B/$f" "%s/$f"
  done
fi
export BRENDA_WORK_DIR="."
mkdir -p "$B"
cd "$B"
"""
```

Again, thanks for the help. Interesting trying to bring brenda back from the dead...

**Comment by njeirath** [comment]
@jldonovan3 apologies, I should have pointed you to the `utils.py` file to save you some time digging that up.  

As for adding `sudo ln /dev/xvdf /dev/xvdf1`, you're exactly right, you should be able to insert that line somewhere towards the top of that script in `brenda/run.py` to get the command to run when the EC2 instance spins up.  That should put the volume in the appropriate location for brenda to pick it up when it starts up.

As for viewing logs on the servers from brenda-web, I would have expected the `brenda-tool` command to have worked, did you get any particular error messages or did it simply not return any data?  An alternative is to access the logs via a web browser.  The way to do that would be to grab the IP address of one of the workers from the dashboard on brenda-web and navigate to the appropriate page in a browser tab.  For example, if your worker IP is 1.2.3.4, you should be able to access it at the address `http://1.2.3.4/log_tail.txt`, this should give you the last 1000 lines of the log to figure out what went wrong.  Typically the worker starts processing frames within a minute or two from when the instance starts up so you should know relatively quickly whether it worked or not.  

In any case, if you discover any bugs with brenda-web while investigating let me know and I can try to get a fix in.

**Comment by jldonovan3** [comment]
Update...
So for some reason, now when I run `brenda-tool` ssh, or try to access the log from the worker IP when using brenda-web, the ec2 instances aren't allowing login as root... it only prints the "please login as ubuntu" message. It looks like there's an issue with cloud.init, because I have my AMI set up to allow root login...I've double-triple-checked. I've only had this issue when trying to attach EBS volumes.

So I just ssh'd into the instance manually and dug up the /brenda/log:

```
RM task_count
RM task_last
MKDIR /mnt/brenda/tmp
Spot request ID: sir-in6i6qbh
MKDIR /mnt/brenda/brenda-project.mount
*** ['/bin/mount', '/dev/xvdf', '/mnt/brenda/brenda-project.mount']
mount: wrong fs type, bad option, bad superblock on /dev/xvdf,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
Traceback (most recent call last):
  File "/usr/local/bin/brenda-node", line 112, in <module>
    main()
  File "/usr/local/bin/brenda-node", line 108, in main
    i.start()
  File "/usr/local/lib/python2.7/dist-packages/brenda/daemon.py", line 90, in start
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/brenda/daemon.py", line 143, in run
    self.func()
  File "/usr/local/bin/brenda-node", line 105, in <lambda>
    func = lambda : node.run_tasks(opts, args, conf)
  File "/usr/local/lib/python2.7/dist-packages/brenda/node.py", line 333, in run_tasks
    proj_dir = get_project(conf, blender_project)
  File "/usr/local/lib/python2.7/dist-packages/brenda/node.py", line 421, in get_project
    utils.mount(dev, proj_dir)
  File "/usr/local/lib/python2.7/dist-packages/brenda/utils.py", line 88, in mount
    system(["/bin/mount", dev, dir])
  File "/usr/local/lib/python2.7/dist-packages/brenda/utils.py", line 24, in system
    raise ValueError("command failed with status %r (expected %r)" % (ret, succeed))
ValueError: command failed with status 32 (expected 0)
```

After doing some digging, it looks like brenda might not actually be mounting the partition `/dev/xvdf1` even if it does attach the EBS volume from the EBS URL. It may be trying to mount the device `/dev/xvdf` instead? I'm not sure. I'm not a Linux/Ubuntu wizard, but would the symbolic link not work between the device and the partition if neither is being mounted correctly? When I try to manually attach the EBS volume via the console to a test instance and run lsblk, it doesn't look like it mounts the EBS volume, even though it does get attached. You have to mount it yourself to the instance. Right now I'm trying to dig around in brenda's code and see how it mounts EBS volumes... not having much luck.

Would adding `sudo mount /dev/xvdf1 /mnt` above the symbolic link command in that script do anything? Or would it conflict with what brenda's already doing?

**Comment by njeirath** [comment]
> So for some reason, now when I run brenda-tool ssh, or try to access the log from the worker IP when using brenda-web, the ec2 instances aren't allowing login as root... it only prints the "please login as ubuntu" message.

I suspect this issue is that older versions of Ubuntu were setup with `root` as the default user to use for SSH while newer versions use `ubuntu` as the user.  It has been a while since I've used the `brenda-tool` but I believe you can pass in a user with the `-u` flag so maybe something like `brenda-tool -u ubuntu` would get you what you need.  Alternatively I believe you can set the `AWS_USER` environment variable to `ubuntu` to get it to SSH using the correct user.

> After doing some digging, it looks like brenda might not actually be mounting the partition /dev/xvdf1 even if it does attach the EBS volume from the EBS URL. It may be trying to mount the device /dev/xvdf instead?

Based on your error message it looks like maybe you updated the devs list in `utils.py` and created your worker AMI image using that updated version?  If that is the case, brenda will use that same code to form the specification for the block device in the EC2 specification as well as where it will look for the device once the EC2 instance is running which would cause it to expect it to be `/dev/xvdf`.  Using one of the existing Brenda AMIs still looks for the mount at `/dev/xvdf1`.

As for the error you're getting, it appears that you might have the snapshot setup with a filesystem type that is unsupported based on the error you get:
```
mount: wrong fs type, bad option, bad superblock on /dev/xvdf,
       missing codepage or helper program, or other error
```

You may try running fsck to verify what filesystem is setup on your device.  I used something like the following as an example:

```
fsck -N /dev/xvdf
fsck from util-linux 2.20.1
[/sbin/fsck.ext2 (1) -- /dev/xvdf] fsck.ext2 /dev/xvdf 

fsck -N /dev/xvdf1
fsck from util-linux 2.20.1
[/sbin/fsck.ext2 (1) -- /dev/xvdf1] fsck.ext2 /dev/xvdf1 
```

Maybe you can describe the steps you went through to build your EBS snapshot as that might help narrow down what the issue is, specifically what OS you used to copy files to the snapshot etc.

As a side note, I dug up an old EBS snapshot I had laying around and was able to kick off a rendering job using brenda-web without any issues.  I've included the top of the log from that machine showing the successful mount of `/dev/xvdf1` to `/mnt/brenda/brenda-project.mount`.  

```
RM task_count
RM task_last
MKDIR /mnt/brenda/tmp
Spot request ID: sir-qyir7xqh
MKDIR /mnt/brenda/brenda-project.mount
*** ['/bin/mount', '/dev/xvdf1', '/mnt/brenda/brenda-project.mount']
PROJ_DIR /mnt/brenda/brenda-project.mount
queue read: <boto.sqs.message.Message object at 0x7fa1b7bd5810>
no task push task
RMTREE /mnt/brenda/brenda-outdir1.tmp
MKDIR /mnt/brenda/brenda-outdir1.tmp
script len: 74
```

**Comment by jldonovan3** [comment]
Hey, again, thanks for the help. I really really appreciate it.

And I think you're right, it probably has something to do with the EBS snapshot I created. I followed James Yonan's instructions manually, since the `rsync `command was way too slow at uploading all the files I needed to place on the volume. It was faster to upload them into an S3 bucket with `s3cmd put`. Here's my steps:
(1) Created a large volume on an instance running Ubuntu (same OS as my AMI used for rendering).
(2) Zipped up my project files on my Windows machine, and uploaded it to an S3 bucket.
(3) Copied over a .zip of my project files from S3 onto the volume at `/mnt`, which is where James Yonan's tutorial says to place the files. 
(4) Unzipped the .zip
(5) Unmounted the directory where the project files were expanded.
(6) Detached the volume from the instance.
(7) Shut down the instance.
(8) Snapshotted the volume.

The snap id for the snapshotted volume is what I placed in the `.brenda.conf` file. 

You mentioned the modification of the `utils.py` folder where I changed `f1` to `f` where Brenda gets its device names from ... I had done that originally because when trying to start up the instance with the snapshot attached as a volume, AWS was giving me the invalid device name error when it was trying to attach the snapshot as `/dev/sdf1` (which then changes to `/dev/xvdf1` on ec2 instances because of that Xen virtualization thing). I'm wondering if Brenda now also tries to mount the project and look for the files in the `/dev/xvdf`, instead of the `/dev/xvdf1` partition? 

Here are the results of running fsck on an instance with my EBS snapshot attached as a volume:
```
fsck -N /dev/xvdf
fsck from util-linux 2.27.1
[/sbin/fsck.ext2 (1) -- /dev/xvdf] fsck.ext2 /dev/xvdf

fsck -N /dev/xvdf1
fsck from util-linux 2.27.1
[/sbin/fsck.ext4 (1) -- /] fsck.ext4 /dev/xvdf1
```
Probably worth noting it doesn't look like AWS automatically mounts volumes you attach to your instance. Does that have to be done manually? 

Maybe if I try to mount `/dev/xvdf` in the startup script, instead of `/dev/xvdf1`, and then hope the symbolic link command that comes right after it does the trick? Then again, I'm not sure why the snapshot device isn't mounting in the first place without me telling it to in the startup script...

**Comment by njeirath** [comment]
It is a bit suspicious that the filesystem type for `/dev/xvdf` is different from `/dev/xvdf1` in your output.  Thinking back to when I setup my EBS volume, I didn't use the brenda-ebs command but spun up an EC2 instance and created the filesystem on the EBS volume manually generally following the instructions  here: [Making an Amazon EBS Volume Available for Use on Linux
](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html).  Not sure if that is the issue or not though.  One other question though is what version of Ubuntu you're using for the worker AMI.

As for your mounting question, the mounting itself is actually handled by the brenda-node application that runs on the worker node itself.  If you look towards the end of the startup script sent to the EC2 instance when it starts up the last thing it does is start brenda-node with something like this:

```
/usr/local/bin/brenda-node --daemon <<EOF
....
BLENDER_PROJECT=ebs://snap-11223344
...
```

It is the brenda-node app itself that actually mounts the volume, the code to generate the command is [towards the end of the node.py file](https://github.com/jamesyonan/brenda/blob/master/brenda/node.py#L409).  The reason I had to add the symlink is because AWS makes the EBS volume available at `/dev/xvdf` while brenda-node expects it to be at `/dev/xvdf1` so the symlink is just a way to get the device in the correct location for brenda-node to pick it up.  Since your file systems appear to be different I'm wondering if there is a partition setup on that EBS and that is what is actually getting mounted on `/dev/xvdf1`?

Another thing you could try to help troubleshoot would be to start up an EC2 instance using your AMI and then actually run through the commands that typically get passed in via the startup script manually.  This might help narrow down where the problem is.  If you go this route I'd recommend changing the `DONE=shutdown` argument for brenda-node to `DONE=exit` so your EC2 instance won't get shutdown while testing.

**Comment by jldonovan3** [comment]
Sure enough, it was the varying filesystem type, and the way my EBS volume was partitioned. I ended up following those instructions from the documentation on a fresh volume, created a filesystem with the right type, copied over my project files from the old volume, and it didn't create a weird partition when I unmounted and snapshotted.

So now it seems everything gets initialized correctly. I ran up an instance with `brenda-run`, ssh'd in, and all the files and directories seem to be in the right place. The project files successfully end up in `/mnt/brenda/brenda-project.mount` on the `/dev/xvdf` device, along with the `brenda-go` script.

Now, the only problem seems that it doesn't want to start up rendering after it sets up the task and runs the frame script:

```
RM task_count
RM task_last
MKDIR /mnt/brenda/tmp
Spot request ID: sir-35ci4e1j
MKDIR /mnt/brenda/brenda-project.mount
*** ['/bin/mount', '/dev/xvdf', '/mnt/brenda/brenda-project.mount']
PROJ_DIR /mnt/brenda/brenda-project.mount
queue read: <boto.sqs.message.Message object at 0x7f0315bc7e10>
no task push task
RMTREE /mnt/brenda/brenda-outdir1.tmp
MKDIR /mnt/brenda/brenda-outdir1.tmp
script len: 144
------- Run script /mnt/brenda/brenda-project.mount/brenda-go -------
#!/bin/bash
/usr/local/blender-2.79-a6f750dd414-linux-glibc219-x86_64/blender -b *.blend -F EXR -o /mnt/brenda/brenda-outdir1.tmp/frame_###### -s 141 -e 141 -j 1 -t 0 -a -noaudio
--------------------------
active task: {'msg': <boto.sqs.message.Message object at 0x7f0315bc7e10>, 'id': 1, 'proc': <brenda.node.Subprocess object at 0x7f0315bc7dd0>, 'retcode': None, 'outdir': '/mnt/brenda/brenda-outdir1.tmp'}
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
******* REASSERT active 1
./brenda-go: line 2:  1417 Killed                  /usr/local/blender-2.79-a6f750dd414-linux-glibc219-x86_64/blender -b *.blend -F EXR -o /mnt/brenda/brenda-outdir1.tmp/frame_###### -s 141 -e 141 -j 1 -t 0 -a -noaudio
RMTREE /mnt/brenda/brenda-outdir1.tmp
******* RETRY 1/5: fatal error in active task
******* WAITING 30 seconds...
queue read: <boto.sqs.message.Message object at 0x7f0315bda2d0>
no task push task
RMTREE /mnt/brenda/brenda-outdir2.tmp
MKDIR /mnt/brenda/brenda-outdir2.tmp
script len: 144
------- Run script /mnt/brenda/brenda-project.mount/brenda-go -------
#!/bin/bash
/usr/local/blender-2.79-a6f750dd414-linux-glibc219-x86_64/blender -b *.blend -F EXR -o /mnt/brenda/brenda-outdir2.tmp/frame_###### -s 140 -e 140 -j 1 -t 0 -a -noaudio
--------------------------
active task: {'msg': <boto.sqs.message.Message object at 0x7f0315bda2d0>, 'id': 2, 'proc': <brenda.node.Subprocess object at 0x7f0315bda250>, 'retcode': None, 'outdir': '/mnt/brenda/brenda-outdir2.tmp'}
******* REASSERT active 2
******* REASSERT active 2
******* REASSERT active 2

```

It eventually fails after retrying so many times. I'm not sure what to do at this point. 

I added the `-noaudio` command at the end of my frame script, because I was getting an error for some audio driver that wasn't present on the instance when I tried running `brenda-run` the first time after fixing the EBS issue. Not sure that would be causing any issues, since it's just telling blender to ignore sound.

**Comment by njeirath** [comment]
Glad to hear you were able to get things further along.  This particular issue you're running into now is not something I've seen but I did see this in the error logs:

```
./brenda-go: line 2:  1417 Killed                  /usr/local/blender-2.79-a6f750dd414-linux-glibc219-x86_64/blender -b *.blend -F EXR -o /mnt/brenda/brenda-outdir1.tmp/frame_###### -s 141 -e 141 -j 1 -t 0 -a -noaudio
```

I'm not positive what `blender-go` is as it doesn't appear to be part of blender but the error suggests that might be where things are going wrong.
