### ISSUE TITLE
Cannot pull task details from custom AMI

### ISSUE THREAD

**Issue by aliasguru** [njeirath/brenda-web#88]
I've created a custom brenda AMI on AWS and am successfully rendering with it. I can use Brenda-web to submit jobs just fine. The only thing I don't know what to do about is an issue in the Dashboard: A few of the details don't update. These are:

- Uptime
- Tasks Completed
- Time/Task
- Cost/Task
- CPU Load

When debugging the site, I noticed in the console that the communication with the AMI failed because of a CORS error. It basically tells me that "No Access-Control-Allow-Origin header is present on the requested resource. This happens when brenda-web tries to read the uptime.txt file from the server.

However, using one of the provided AMIs works just fine. So my question really is:
What do I need to do to enable CORS communication in my custom AMI?

The exact error in Firefox (German I'm afraid):
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://54.236.31.153/uptime.txt?d=1508143629217. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

**Comment by njeirath** [comment]
@aliasguru Can you specify which version of Ubuntu your AMI was based off of?

The quick answer is to reference the very last section named "Nginx Path" in the [Tutorial](http://brenda-web.com/#/tutorial) and validate that the "Nginx Path" field is being set appropriately on the "Setup Job" tab under the "Add Workers" section (this will depend on the version of Ubuntu you used). 

Some more background on why the issue may be occurring:

CORS is a security mechanism implemented by most browsers to prevent web applications from making calls to servers on a different domain [CORS details](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).  This occurs in the dashboard because the domain of the site is brenda-web.com (or localhost if running locally) and this page is trying to access data on a different domain (54.236.31.153 in your case).  To prevent this from being an error, HTTP provides for the _Access-Control-Allow-Origin_ header which can be set to a particular domain on the server or simply '*' to allow all origins.

To serve up the data from each of the workers to drive the dashboard functionality we install a light weight web server [Nginx](https://www.nginx.com/).  This is automatically installed by the startup script when brenda-web starts up an EC2 instance.  We setup a couple cron jobs to push relevant files to the folder where nginx serves up files and also set the _Access-Control-Allow-Origin_ header to '*' to allow all cross domain connections.

The full startup script can be seen on the brenda-web site under the "Setup Job" tab at the very bottom in the text area labeled "Startup Script", I've pulled out the relevant portion of the script below:

```
sudo apt-get -y install nginx
sudo sed -i '29 i\ add_header 'Access-Control-Allow-Origin' '*';' /etc/nginx/sites-enabled/default
sudo echo "* * * * * root tail -n1000 /mnt/brenda/log > /usr/share/nginx/html/log_tail.txt" >> /etc/crontab
sudo echo "* * * * * root cat /proc/uptime /proc/loadavg $B/task_count > /usr/share/nginx/html/uptime.txt" >> /etc/crontab
if ! [ -d "$B" ]; then
  for f in brenda.pid log task_count task_last DONE ; do
    ln -s "$B/$f" "/root/$f"
    sudo ln -s "$B/$f" "/usr/share/nginx/html/$f"
  done
fi
sudo service nginx restart
```

The high level steps in the script are to
1. Install nginx
2. Setup the Access-Control-Allow-Origin header in the nginx configuration
3. Setup a few cron jobs to populate the directory from which nginx serves web pages
4. Restart nginx

Since you're receiving the CORS error that suggests that something went wrong during the startup process and the appropriate headers weren't set in the nginx config file.  If you're able to make it public, the AMI ID you're using would help so I can spin up a worker to see what might be going on.  Otherwise any logs you're able to provide from the worker startup would be helpful or at the very least the version of Ubuntu you're using.

**Comment by njeirath** [comment]
@aliasguru One thing you can try as a quick test would be to start up a worker, SSH into it and remove one of the "Access-Control-Allow-Origin" lines from the nginx config and restart the service and see if the dashboard starts working (might take ~30 seconds to a minute after the restart).  If that works it would suggest nginx can't handle having 2 of those lines in the config and probably uninstalling nginx and rebuilding the AMI would probably be the easiest approach.

If that does in fact end up being the issue let me know and I can put in a check to see if the header is already set in the config file before adding it again.

**Comment by aliasguru** [comment]
@njeirath Have tried above suggestions, but no luck. The instance would still not allow any CORS communication after editing the default file and restarting nginx service. I then ssh'd into it again, purged nginx and created another custom AMI. When spinning that one up, nginx is installed via the script just fine, the "Access-Control-Allow-Origin" is now only present once. Still: No CORS communication possible. There must be something else.

I think as a next step I might just go ahead and reinstall everything on a new instance, which I run from your existing 2.79 AMI. Maybe then I have my tools working AND communication happening with the instance. Still wonder what the issue could be.

**Comment by aliasguru** [comment]
I think I found a little difference between the /etc/nginx/sites-enabled/default files on our AMIs. Yours reads:

server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	root /usr/share/nginx/html;
	index index.html index.htm;

	# Make site accessible from http://localhost/
	server_name localhost;
 add_header Access-Control-Allow-Origin *;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
		# Uncomment to enable naxsi on this location
		# include /etc/nginx/naxsi.rules
	}


mine reads:
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	# SSL configuration
	#
	# listen 443 ssl default_server;
	# listen [::]:443 ssl default_server;
	#
	# Note: You should disable gzip for SSL traffic.
	# See: https://bugs.debian.org/773332
	#
	# Read up on ssl_ciphers to ensure a secure configuration.
 add_header Access-Control-Allow-Origin *;
 add_header Access-Control-Allow-Origin *;
	# See: https://bugs.debian.org/765782
	#
	# Self signed certs generated by the ssl-cert package
	# Don't use them in a production server!
	#
	# include snippets/snakeoil.conf;

	root /var/www/html;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

So it seems like there are different versions of nginx or at least the configuration file in use. Their order and content is quite different. I'm clueless as of how that's possible.

**Comment by aliasguru** [comment]
SUCCESS! I've ssh'd into another running instance now, and manually edited the /etc/nginx/sites-enabled/default file, entering the exact details which you have in yours. Once done and restarted nginx, the instance shares all details!

**Comment by aliasguru** [comment]
After further examination, two conditions need to be met:

1) the root path must match the one given by brenda-web on task submission
2) there must not be a double Access-Control-Allow-Origin line

Only if both conditions are met, the machines talk to each other.

**Comment by njeirath** [comment]
@aliasguru Great, glad you got it working and thanks for the explanation of what you found.  I may try to build a replacement for nginx as that's the second time a version difference has bit me.  Should hopefully help alleviate some of these issues in the future.
